### ISSUE TITLE
dis_boundary的一些问题

### ISSUE THREAD

**Issue by sanfenzhongmeichifanle** [LuZaiJiaoXiaL/HRHD-HK#1]
![image](https://github.com/LuZaiJiaoXiaL/HRHD-HK/assets/133829083/28fab871-d61e-49aa-9f88-511f43d6357b)
您好，我看您边界处理的代码部分并没有涉及dis_boundary的计算，这是为什么？

**Comment by maosuli** [comment]
我们只提供了数据，并没有提供代码呢

**Comment by sanfenzhongmeichifanle** [comment]
抱歉，发错了。但是您考虑提供相关代码吗？
